### ISSUE TITLE
Ssl Verification Failed

### ISSUE THREAD

**Issue by rawpie2** [FrogTheFrog/moondeck-buddy#10]
Im using sunshine set up correctly, but when I try to pair on my steam deck it says "Ssl Verfication Failed"

**Comment by FrogTheFrog** [comment]
Please use the latest release version and not a pre-release as the matching version is not yet on decky store

**Comment by cohaolain** [comment]
I'm seeing this even with both MoonDeck and Buddy on v1.3.0 - though I did previously have Buddy v1.3.1 installed, I uninstalled it before installing Buddy v1.3.1.

**Comment by FrogTheFrog** [comment]
> I'm seeing this even with both MoonDeck and Buddy on v1.3.0 - though I did previously have Buddy v1.3.1 installed, I uninstalled it before installing Buddy v1.3.1.

Moondeck needs to be on 1.4.0. The versions are independent. Basically the latest Moondeck release works with the latest Buddy version.

For Testing store, there usually is a pre-release version of Buddy.

**Comment by cohaolain** [comment]
Hey, figured this out immediately after I posted my comment, sorry! Many thanks for taking the time to reply.
