### ISSUE TITLE
Question. Can this be used to play couch coop on two steam decks? 

### ISSUE THREAD

**Issue by JamesGrant88** [FrogTheFrog/moondeck-buddy#100]
Hi

this might be a really niche usage but currently me and my wife use Steam Remote Play to play couch coop games. It’s unreliable however and looking for solutions. 

Before I invest too much time, does this program work as an alternative solution? I’ve installed it on my steam deck but struggling to work out how to add it to sunshine. 

Thanks,
James

**Comment by FrogTheFrog** [comment]
Hi.

Probably yes.

If you can get the Sunshine + Moonlight to get work (for 1 host + 2 steamdecks - 2 channels will have to be configured in Sunshine in this case) there shouldn't be a problem with MoonDeck. At least I don't remember anything in the code that would explicitly prevent 2 clients from working at the same time.

MoonDeck's main function is to start a new stream + a game or attach itself to a running game stream (in case SteamDeck got disconnected or something). Since one client would be starting a game stream and another would be just attaching, it should work?

**Comment by JamesGrant88** [comment]
> Hi.
> 
> Probably yes.
> 
> If you can get the Sunshine + Moonlight to work (for 1 host + 2 steamdecks - 2 channels will have to be configured in Sunshine) there shouldn't be a problem with MoonDeck. At least I don't remember anything in the code that would explicitly prevent 2 clients from working at the same time.
> 
> MoonDeck's main function is to start a new stream + a game or attach itself to a running game stream (in case SteamDeck got disconnected or something). Since one client would be starting a game stream and another would be just attaching, it should work?

Thanks for such a quick reply! 

not sure if wires crossed but it’s purely using steam decks, no host pc. I’ll keep trying to configure it but sunshine is configured and running but on the other steam deck it’s not finding any hosts.

**Comment by FrogTheFrog** [comment]
I don't think I'll be much of a help here. I think Sunshine needs to be run from the gamemode and also you might want to enter the IP manually instead of relying on the "find" functionality.

**Comment by JamesGrant88** [comment]
> I don't think I'll be much of a help here. I think Sunshine needs to be run from the gamemode and also you might want to enter the IP manually instead of relying on the "find" functionality.

Thank you.

So after a little playing last night I managed to get it working with sunshine and the normal moonshine app running as a non steam app. I had to enter the IP manually. Unfortunately doing it using your plugin didn't see the device but at least I have a solution now :)

**Comment by FrogTheFrog** [comment]
> > I don't think I'll be much of a help here. I think Sunshine needs to be run from the gamemode and also you might want to enter the IP manually instead of relying on the "find" functionality.
> 
> Thank you.
> 
> So after a little playing last night I managed to get it working with sunshine and the normal moonshine app running as a non steam app. I had to enter the IP manually. Unfortunately doing it using your plugin didn't see the device but at least I have a solution now :)

I think you would have to also enter the IP manually in MoonDeck and also start Buddy in gamemode.

However, I don't think that MoonDeck really suits this usecase. There is little point of using it if you don't need automation for launching games :thinking:, which I think is always the case in co-op... Also, no point in using MoonDeck to shutdown or wakeup another steamdeck.
