### ISSUE TITLE
No Buddy connection to Bazzite gamemode host

### ISSUE THREAD

**Issue by jonnypanic** [FrogTheFrog/moondeck-buddy#102]
I have managed to successfully get it all running on a Bazzite PC running in desktop mode, streaming to Steam Deck. But I usually use my PC in gamemode. When I switch to gamemode, the Buddy connection is lost. Moonlight and Sunshine, however, continue to work fine regardless of mode. 

I wonder if there's something I've done wrong, or is this an issue with Bazzite gamemode. Perhaps Buddy can't run in the background?

Thanks. I love the plugin, so it'd be really cool if this worked.

**Comment by FrogTheFrog** [comment]
Buddy is not auto-started as a service, but instead it uses other desktop environment based approach. So, maybe it's simply not started?

**Comment by jonnypanic** [comment]
That seems to be the case, yes. I just tried opening Nested Desktop on the host, and then it works fine. Closing Nested Desktop closes Buddy, I guess. Do you know of a way to autostart it so it can run in the background in gamemode?

**Comment by FrogTheFrog** [comment]
First disable the Buddy's autostart functionality, then create your own `systemd` user unit file.
Something along the lines of:
1. Create user file `~/.config/systemd/user/moondeckbuddy.service`
2. Enable the service `systemctl --user enable moondeckbuddy`

For unit file example and further reference check https://wiki.archlinux.org/title/Systemd/User
Make sure it is started `After=network.target`

**Comment by jonnypanic** [comment]
Great, thanks a lot.

**Comment by jonnypanic** [comment]
I have created the unit file, and it autoboots and works in desktop mode no problem, but does not when in gamemode. So, I am at a loss as to why. Maybe this is a Bazzite specific problem. 

For reference, this is the file I made:

[Unit]
Description=moondeckbuddy
After=network.target
StartLimitIntervalSec=500
StartLimitBurst=5

[Service]
Type=simple
WorkingDirectory=/home/bazzite/Applications/
ExecStart=/home/bazzite/Applications/MoonDeckBuddy-1.6.2-x86_64.AppImage
Restart=on-failure

[Install]
WantedBy=graphical-session.target

**Comment by FrogTheFrog** [comment]
I know from previous experience that `DISPLAY` variable is not exported when running gamescope and Buddy needs to for system tray...

Try the following:
```
[Unit]
Description=moondeckbuddy
After=network.target
StartLimitIntervalSec=500
StartLimitBurst=5

[Service]
Type=simple
Environment="DISPLAY=:0"
WorkingDirectory=/home/bazzite/Applications/
ExecStart=/home/bazzite/Applications/MoonDeckBuddy-1.6.2-x86_64.AppImage
Restart=on-failure

[Install]
WantedBy=graphical-session.target
```

**Comment by jonnypanic** [comment]
That fixed it, all seems to be working perfectly now with MoonDeckBuddy, so ill close the issue. 

Thanks a lot.
