### ISSUE TITLE
Request to add confirmation box

### ISSUE THREAD

**Issue by gdiazbanuelos** [FrogTheFrog/moondeck-buddy#104]
Hello!
I love this tool so much! One thing that annoys me is sometimes I accidentally select the Moondeck buddy button on a game page when trying to navigate to controller or game settings.

Is there a way in the config settings to add a confirmation box (Launch stream?: yes/cancel)? I would like to avoid accidentally launching a game and having to close out of it since there is no prompt to confirm launching.

Let me know if that is possible. Thank you!

**Comment by FrogTheFrog** [comment]
@gdiazbanuelos Please get the latest version from the Testing store. There will be an option to enable the prompt in `Shortcut settings` sub-page.

**Comment by FrogTheFrog** [comment]
Box added in 1.8.1
