### ISSUE TITLE
Cannot Pair MoonDeckBuddy with Windows Sunshine host

### ISSUE THREAD

**Issue by Doc-4** [FrogTheFrog/moondeck-buddy#22]
It was necessary to whitelist MoonDeckBuddy's executables in windows' firewall to get steam deck to see it as not paired, rather than offline. You might want to add that as a step in setup. After doing so, attempting to pair it generates codes that always result in "Pairing Failed: Check if the PIN is typed correctly" from sunshine's web GUI.

**Comment by FrogTheFrog** [comment]
Heyo.

So you want some thing like:
> Whitelist MoonDeckBuddy in Windows' firewall so that the app can be reached from outside the host PC.

When you click pair in MoonDeck, a popup input window from MoonDeckBuddy should become visible on the host. This is where you're supposed to enter the pin number.

**Comment by Doc-4** [comment]
> Heyo.
> 
> So you want some thing like:
> 
> > Whitelist MoonDeckBuddy in Windows' firewall so that the app can be reached from outside the host PC.
> 
> When you click pair in MoonDeck, a popup input window from MoonDeckBuddy should become visible on the host. This is where you're supposed to enter the pin number.

Yes to the first part, I knew to do it but others might not.
Interesting, I got no such window as a popup when pushing pair, I'll double check that I have the necessary runtimes, are there any other components this relies on to display such a message?

**Comment by FrogTheFrog** [comment]
Nope, it uses Qt6 framework, which uses Windows API in the end. So Windows redistributables should be enough. Try enabling the debug logs for Buddy, maybe something interesting will pop up?

**Comment by Doc-4** [comment]
> Nope, it uses Qt6 framework, which uses Windows API in the end. So Windows redistributables should be enough. Try enabling the debug logs for Buddy, maybe something interesting will pop up?

I was missing the very latest runtime, figures. That fixed that problem, but now I get "Failed to find application MoonDeckStream" from the running flatpak after attempting to load appids.

**Comment by FrogTheFrog** [comment]
You will get this error if it's not added to the Sunshine OR sometimes something gets stuck on either the Sunshine or Moonlight and it does not refresh the list.

I would recommend to forget the host on Moonlight and add it again.

**Comment by Doc-4** [comment]
Forgot the host, repaired them, rebooted both machines and tested it, same error message. If there's a log you want me to send you, let me know where it would be.

**Comment by Doc-4** [comment]
Forgot the host, repaired them, rebooted both machines and tested it, same error message. If there's a log you want me to send you, let me know where it would be.

**Comment by FrogTheFrog** [comment]
Ugh, I guess I will have to start with some basic debugging questions:

1. Have you migrated from sunshine <0.16 to newer versions? If yes then have you reinstalled it completely? There are some strange issues if you don't do it :/.
2. Have you added MoonDeckStream to sunshine?
3. Can you manually launch MoonDeckStream from Moonlight?
4. If you had GFE before Sunshine, did you remove that entry from Moonlight? Moonlight's cmd is not case-sensitive when asked to start stream for `<hostname>` and if there are similar hostname entries, an incorrect one can be chosen.

**Comment by Doc-4** [comment]
Went through this and didn't realize there were specific setup instructions for moondeckstream.exe with sunshine on host. I was going off the instructions from the decky plugin, guess I should have read both sets. I'm going to assume that's the only real issue here for the moment and close this, as my sunshine is brand new and 18.0, and I've never had GFE on this machine. 

I'll set it up next week, going away shortly. Sorry if it was any trouble, and thank you for the help.
