### ISSUE TITLE
GeForce experience returned error. (Error 0)

### ISSUE THREAD

**Issue by RobertAdams313** [FrogTheFrog/moondeck-buddy#24]
Getting this error. Any ideas? I used to use moon deck previously but wanted to try it again with Sunshine and getting this error.

**Comment by FrogTheFrog** [comment]
Could be any reason really, incorrect path or something else. You'll have to debug this using logs from sunshine (located in the WEB UI) and moonlight (located in `/tmp/moondeck-runner-moonlight.log`

**Comment by FrogTheFrog** [comment]
So did you manage to figure it out?

**Comment by RobertAdams313** [comment]
Yes I actually did figure it out. It was an inccorrect path as you mentioned. Once I corrected that, it loads fine. Thanks!
