### ISSUE TITLE
[Feature Request] Automated setup

### ISSUE THREAD

**Issue by KingIzzymon** [FrogTheFrog/moondeck-buddy#25]
Could we add an automated setup script?

Features:
- Install MoonDeckBuddy
- Install Sunshine
- Configure Sunshine
  - Add 'MoonDeckStream' entry to "C:\Program Files\Sunshine\config\apps.json"
  - Configure default display & audio (autoselect default and/or let user select and confirm)
- Optional: Create shortcuts for autostart of MoonDeckBuddy & Sunshine
- Optional: Install ViGEmBus / [ViGEmBus 2](https://github.com/ViGEm/ViGEmBus/issues/139)

**Comment by FrogTheFrog** [comment]
Feel free to create a PR for such a script, I personally don't have time to work on this as it seems to be too much effort for a very little reward (at first glance).

**Comment by KingIzzymon** [comment]
Yep I totally understand. I'll whip something together this week and submit a PR. Which branch should I submit to?

**Comment by FrogTheFrog** [comment]
I have created the `install_script` branch for you. Please use that one.

That aside I use the NSIS installer that comes with CMake, if you can please try to integrate this into the installer (just a request). If you do decide to do this feel free to completely butcher whatever CMake has by default.

**Comment by KingIzzymon** [comment]
Sounds good, will do

**Comment by FrogTheFrog** [comment]
I'm closing this as there seems to be no progress anymore.
