### ISSUE TITLE
Steam Big Picture window covering game on launch

### ISSUE THREAD

**Issue by XenHat** [FrogTheFrog/moondeck-buddy#26]
Since a few updates on either the Host's steam client or something else I can't pinpoint, I have been having issues with remote play on a Windows host: The Steam Big Picture window covers the game with an infinite loading animation, providing a confusing feedback, as the game does indeed launch correctly in the background (I can hear the game menu music).

Would it be possible to resolve this? Ideally, not using Big Picture mode unless requested would work, assuming Gamescope still works in "desktop" client mode.
Failing that, closing the "Steam Big Picture" window would suffice as it works around the issue. However I have to walk to the computer to do this every time I start the game, or the game crashes.

P.S. The issue doesn't happen if the game is launched in desktop mode prior to connecting.

![image](https://user-images.githubusercontent.com/980408/224512170-c956149d-f2d9-4187-ac8f-c8f8f448c4de.png)
![image](https://user-images.githubusercontent.com/980408/224512137-076fda01-6809-465f-9f90-8a2c38fde2c0.png)
![image](https://user-images.githubusercontent.com/980408/224512152-2408355f-ee30-4290-8c87-a9912aa93e7a.png)

**Comment by FrogTheFrog** [comment]
I will probably not have time to do anything about this unfortunately (for a month or so). You could try to remove 'big picture' launch options from the 'launchApp' method and it might just work.

That aside, have you tried Steam client beta? It mentions something exactly like the issue that you have https://store.steampowered.com/news/group/4397053/view/3642887728426098465

**Comment by Maz111111** [comment]
I do have this issue only when playing Fallout 4. It may depend on the loader. I don't know.
Workaround:
You have to set Back Button Timeout in sunshine to a value over 0 (mine is set to default of 2000)
start the game on the steam deck as usual
when it comes to this infinitive loading screen 
Press and hold the left little button between thumbstick and d-pad (should be the back button on a xbox controller) 
This will trigger the steam Menu.
choose the first entry (I don't know what this is called on an english deck - directly translated it is called Startpage maybe on the deck it is called homepage)
Choose the game which is currently running in the background and click resume.
Tada

**Comment by FrogTheFrog** [comment]
I can seem to replicate this issue with either stable or beta version of Steam client :/. Could any of you try to remove the userdata from the Steam directory? Or better, get a fresh install of Steam somewhere?

**Comment by Maz111111** [comment]
So I tried deleting the userdata folder on a other PC with nvidia gamestream but without any visible success. After click play in the loader the game launches but stays in the background as described.
It doesn't bother me since it only affects Fallout 4 anyway. My workaround is enough for me.
I also have no way of enabling a fresh install of Steam.

**Comment by XenHat** [comment]
> I can seem to replicate this issue with either stable or beta version of Steam client :/. Could any of you try to remove the userdata from the Steam directory? Or better, get a fresh install of Steam somewhere?

Unfortunately, this issue is difficult to trigger on purpose. Ideally I would like an option to disable launching the game bia big picture inside moondeck, but that's beyond my current understanding of the codebase.
I have been using my modified binary for the time being as I just want to relax, but if it happens again I would be happy to help diagnosing and maybe orchestrate a fix :)

**Comment by XenHat** [comment]
Apologies, I've been super busy and distracted. I'll do some tests soon!

**Comment by XenHat** [comment]
I'll continue testing over the course of the next few days, but so far, it seems to work fine on the latest Moondeck, Moondeck-buddy and Steam Client versions 😄 
I wonder if this was just a transient bug on the steam side and if it had nothing to do with moondeck in the first place.
