### ISSUE TITLE
"Failed to find application MoonDeckStream"

### ISSUE THREAD

**Issue by rmb707** [FrogTheFrog/moondeck-buddy#27]
I followed the instruction in the troubleshooting section to no avail.
I've uninstalled and re-installed everything

This happens using sunshine and GFE

It all shows online but when I start a game I get that error.
I can use moonlight just fine.

**Comment by FrogTheFrog** [comment]
Did you really add MoonDeckStream app entry to the Sunshine app list?
https://github.com/FrogTheFrog/moondeck-buddy/wiki/Sunshine-setup

If yes, then please check the Sunshine's log output via the WebUI. What's the error code for when it fails to launch MoonDeckStream?

**Comment by rmb707** [comment]
No I’m an absolute nob -.- 
Thank you
