### ISSUE TITLE
When my desktop resolution is set to 1280x800 to fill the Deck's entire screen, and my moonlight settings are also set for 1280x800, MoonDeck stretches things vertically.

### ISSUE THREAD

**Issue by sevansup** [FrogTheFrog/moondeck-buddy#3]
It appears that MoonDeck chooses 720p, even when my desktop resolution is 1280x800. Or perhaps this is something caused by Big Picture mode. Basically, when I don't use MoonDeck, I am able to successfully get games like Valheim to run full screen in 1280x800 without stretching or letterboxing . But with MoonDeck, I had to go into Moonlight's settings (the flatpak app on Deck) and change the resolution to 720p instead of 1280x800 in order for it to not stretch the picture vertically. However, it how has the black letterboxing on top and bottom.

Not a huge issues but I expect there is a relatively easy fix for this. Thanks for working on this plugin! It's awesome. Would love non-Steam game support eventually if that's a possibility.

To add further clarification about my setup (though I don't think any of this matters), I use a HDMI dummy plug on my desktop and I have set the resolution of that to 1280x800. My regular monitor is a big ultrawide display, which was causing issues via streaming, but with the dummy plug set up properly, when I'm not using my desktop and my monitor is off, Windows will default to using the dummy plug as my main monitor. This makes it easy and automatic for me to play games wither at my desktop or streaming, without having to go and change the resolution every time. It has worked great for me via moonlight so far, but moondeck seems to ignore the 1280x800 for whatever reason and just wants 720p.

**Comment by FrogTheFrog** [comment]
When you say `I am able to successfully get games like Valheim`, does it mean you launch them like `Moonlight -> Steam -> Valheim` or `Moonlight -> Valheim`?

As for the non-Steam games, there are no plans  for it at the moment as you can just create a shortcut to them directly in the Moonlight.

**Comment by FrogTheFrog** [comment]
Nevermind, I see what you mean. It seems that launching the stream via Steam forces the incorrect resolution. I will need to bypass it altogether and use some helper process to start/end the stream.

**Comment by FrogTheFrog** [comment]
I will focus my work on this as it now annoys me as I've noticed it thanks to you :/, but no promises for when it will be done as the holidays are coming...

**Comment by sevansup** [comment]
Interesting. I wonder if the new big picture mode will fix this. Thanks for looking into it! Seriously the plug-in has been AWESOME - really a great seamless way to stream games. If I could add one additional recommendation it would be the ability to suspend the host PC, in that same menu where you have the option to shut it down or wake it.

**Comment by FrogTheFrog** [comment]
@sevansup the new big picture mode breaks everything :D. I mean it breaks NVidia's streaming helper and in turn it breaks MoonDeck... Might have to reinvent the wheel if it's not fixed when it goes live into stable.

That aside the resolution thing should work properly now. Please grab the latest Buddy pre-release and MoonDeck from the "Testing" store.

**Comment by sevansup** [comment]
Can confirm this new version fixes the issue! Thanks again!
