### ISSUE TITLE
Games don't open automatically 

### ISSUE THREAD

**Issue by hlebushekhub** [FrogTheFrog/moondeck-buddy#31]
Whenever I open MoonDeck, it just opens Steam, not in BPM or even the game itself, just Steam launcher. Don't know what the deal with it and how I could handle it

**Comment by FrogTheFrog** [comment]
Hi,

try the following, maybe it's related:
https://github.com/FrogTheFrog/moondeck-buddy/wiki/Troubleshooting#windows-steams-big-picture-mode-is-launched-but-not-the-game

**Comment by hlebushekhub** [comment]
Hey @FrogTheFrog. Thanks for the tip, sadly, it didn't work. Problem is, typing a command on terminal while streaming Desktop in moonlight is working, it opens the game as it should from new BPM. But with MoonDeck it's not even opening BPM, I just stuck on Home page. Don't know what can I do to solve it

**Comment by FrogTheFrog** [comment]
Please enable Buddy's debug logs (check wiki) and post it here after trying to run a game.

**Comment by hlebushekhub** [comment]
Here's the log

**Comment by hlebushekhub** [comment]
Here's the log!

[moondeckbuddy.log](https://github.com/FrogTheFrog/moondeck-buddy/files/11276160/moondeckbuddy.log)

**Comment by FrogTheFrog** [comment]
Ok, so from the log I see that it's waiting for MoonDeckStream.exe to start, but it doesn't. Can you post a log from Sunshine? You can access it from the webUI. I'm only interested in the part where it tries to start MoonDeckStream

**Comment by hlebushekhub** [comment]
[sunshine log.txt](https://github.com/FrogTheFrog/moondeck-buddy/files/11276445/sunshine.log.txt)
Okay! Here's sunshine log with one attempt to start a game via moondeck

**Comment by hlebushekhub** [comment]
So I reinstalled Sunshine and MoonDeck and apparently it works! Would tinker a bit more to fully understand if it is
