### ISSUE TITLE
Buddy not starting on startup but on logon

### ISSUE THREAD

**Issue by SentenOnGithub** [FrogTheFrog/moondeck-buddy#33]
Hi there,

First things first: Thanks a lot for your effort!

I liked to use MoonDeck instead of Steam-InHomeStreaming because it gave me the opportunity to remotely wake up my rig and start up a steam game with neither having to set steam to autostart with saved credentials, nor having to remove my hosts local authentication. During the initial game startup I used to be shown the windows login screen and was able to enter my password via SteamDeck-OnScreenKeyboard.

Now (maybe related to the update to Buddy1.5) buddy stays offline until my windows user has logged on.
I already tested installing buddy as a service to no success.

Here the steps to recreate:

(assume sunshine is already configured)
1. Fresh install of buddy
2. Fresh install of MoonDeck plugin
3. Set buddy to start with windows
4. Pair MoonDeck with buddy
5. Shutdown Server
6. WoL from MoonDeck
7. Server starts up and requires PIN/Password to login
8. In MoonDeck GameStream comes online / Buddy does not
9. Manually login to the server
10. Buddy starts and comes online in MoonDeck

Thank you in advance!

**Comment by FrogTheFrog** [comment]
I always like getting issues that are solved without me doing anything :smile:
