### ISSUE TITLE
Are non-Steam games an impossibility?

### ISSUE THREAD

**Issue by SegaBoy64** [FrogTheFrog/moondeck-buddy#34]
I understand this is not currently possible, however will that always be the case.

I'd like to Remote Play games I've added to Steam from other launchers.

Thanks...

**Comment by FrogTheFrog** [comment]
Yes, I don't plan to add support for them, because Steam does not provide a reliable way of tracking their process state.

You can add those games to Sunshine directly and import it via MoonDeck if you want.
