### ISSUE TITLE
Question: streaming non-steam game

### ISSUE THREAD

**Issue by francois-pasquier** [FrogTheFrog/moondeck-buddy#36]
Hi, would it be achievable to use moondeck to stream non-steam game based on its name?

edit: nevermind,, I searched moondeck issues but it’s already been asked on this repo

**Comment by FrogTheFrog** [comment]
> Hi, would it be achievable to use moondeck to stream non-steam game based on its name?
> 
> edit: nevermind,, I searched moondeck issues but it’s already been asked on this repo

For what it's worth, you can add Sunshine apps via MoonDeck
