### ISSUE TITLE
[New Feature] KDE/Wayland

### ISSUE THREAD

**Issue by XenHat** [FrogTheFrog/moondeck-buddy#37]
To pick up where #15 left off, I am willing to assist in developing a workaround for the moondeck-buddy under Wayland using `kscreen-doctor` which is the recommended way to control kwin (KDE's window manager) under Wayland.

Let me know if there's any interest. I have several monitors (3) and machines (2+1) running wayland I can test with.

Checklist:
- [ ] Monitor disabling
- [ ] Monitor resolution change
- [ ] Support X11 as well?

**Comment by FrogTheFrog** [comment]
Also, FYI, Sunshine will implement a feature where it will provide you with "desired" resolution for use in the `do/undo` commands, therefore please stick only to the `Monitor resolution change` part.

I don't want to implement anything more than necessary if this can also be done with Sunshine. (https://github.com/LizardByte/Sunshine/pull/1096)

**Comment by FrogTheFrog** [comment]
Or maybe you could sync on that Sunshine feature and try to implement it yourself :D ?

**Comment by XenHat** [comment]
Having sunshine do the heavy lifting and exposing the required information for the existing code to function is certainly preferable. I shall continue using my do/undo script for the time being then!
