### ISSUE TITLE
Problem with autostart.

### ISSUE THREAD

**Issue by hlebushekhub** [FrogTheFrog/moondeck-buddy#48]
After upgrading to a newest version (v1.5.3), MoonDeck stopped autostarting on PC. The programm is registered to autostart and it has a shortcut in Autostart folder so I don't have an idea what is wrong. I've decided to try create a batch file with open command and put in on Autostart folder too but no luck

**Comment by FrogTheFrog** [comment]
Sorry, but this seems to be Windows issue and I have no idea what could be even wrong...

Maybe it's somewhat related to this https://github.com/FrogTheFrog/moondeck-buddy/issues/33#issuecomment-1508081888 ?

**Comment by hlebushekhub** [comment]
> Sorry, but this seems to be Windows issue and I have no idea what could be even wrong...
> 
> Maybe it's somewhat related to this [#33 (comment)](https://github.com/FrogTheFrog/moondeck-buddy/issues/33#issuecomment-1508081888) ?

Yes! It absolutely is. Just moved moondeck's folder to a public folder and it works now! thank you very much
