### ISSUE TITLE
Sunshine Pairing issue

### ISSUE THREAD

**Issue by CooknBeans** [FrogTheFrog/moondeck-buddy#5]
Hello, Followed the steps and I'm up to the buddy pair. Getting Pairing Failed: Check if the PIN is typed correctly error when entering the PIN. Tried a few times and restarted a few times same error.

**Comment by CooknBeans** [comment]
Never mind. Sorted. Cheers.

**Comment by FrogTheFrog** [comment]
> mind relaying your experience? I'm having the same issue and unsure what is causing the problem

Are you trying to pair MoonDeck + Buddy or Sunshine + Moonlight?

**Comment by FrogTheFrog** [comment]
Well then this is the checklist:
1. Make sure the Nvidia's Gamestream service is disabled.
2. Make sure you don't enter a space by accident at the end of the 4th digit.

Otherwise go ask for help in Moonlight's discord :/

**Comment by FrogTheFrog** [comment]
https://discord.gg/moonlight-stream-352065098472488960

**Comment by the-cucco** [comment]
Disabling Gamestream did it! It connects now. Thank you very much

**Comment by FrogTheFrog** [comment]
> I have the same problem here, if i disable the nvidia gamestream, my moonlight on phone can connect to PC coz it asks to able the gamestream

That just mean Sunshine is not properly running, try restarting the PC or go to Sunshine/Moonlight discords to figure it out
