### ISSUE TITLE
Failed to launch steam app via Buddy!

### ISSUE THREAD

**Issue by francois-pasquier** [FrogTheFrog/moondeck-buddy#57]
With a new desktop, I can't manage to have moondeck running nicely.

Here is what happens:
- I click the moon icon
- Starting MoonDeckStream...
- Sometimes I see the desktop of the host then it gives me `Failed to launch steam app via Buddy!`, sometimes it's just the message.

In the meantime, I can see the resolution changing on the host but I only see steam big picture and the game after moondeck gives me the error.

It's a brand new install of windows, everything is up to date
I tried increasing every runner settings to 60 to no avail.

Nothing interesting in the logs either

**Comment by FrogTheFrog** [comment]
Do you have AMD card?

**Comment by francois-pasquier** [comment]
No, it's an nvidia 4080. In my other desktop I am using an nvidia 1080ti

**Comment by FrogTheFrog** [comment]
Ah, yes not the GPU, but CPU. I was wondering if it's related to this:
https://github.com/FrogTheFrog/moondeck-buddy/issues/41#issuecomment-1627467014

**Comment by francois-pasquier** [comment]
Indeed, disabling the integrated graphics fixed the issue!

I hope it can be fixed in the future :((

Thank you very much, amazing plugin!
