### ISSUE TITLE
Unable to pair with steam deck

### ISSUE THREAD

**Issue by superboo07** [FrogTheFrog/moondeck-buddy#59]
Moondeck buddy shows as offline in my deck at all times despite it being open. I was able to get gamestream server to connect after a lot of frustration but I don't see where I can go from here considering I have it running

**Comment by FrogTheFrog** [comment]
Try setting Buddy to use `TlsV1_2` if you're not on Windows 11. See https://github.com/FrogTheFrog/moondeck-buddy/wiki/Buddy-configuration#ssl-protocol
