### ISSUE TITLE
Option For Sleep PC instead of Shutdown PC

### ISSUE THREAD

**Issue by Salivala** [FrogTheFrog/moondeck-buddy#6]
Wake on lan seems to be easier to get working with the PC when it's sleeping. Would be awesome if you could let it sleep as well

**Comment by FrogTheFrog** [comment]
I will add this to my TODO list, but I would expect this to be added next year (given that holidays are coming).

That aside, there shouldn't be any problems with WOL from a turned off state unless something is mis-configured. In my case once I install proper Intel drivers on my PC, I still need to turn off a "quick-startup" power setting in Windows and disable LAN "sleep" mode in BIOS. This keeps the LAN port powered-on while it's completely shutdown.

Maybe you have similar issues?

**Comment by FrogTheFrog** [comment]
@Salivala An option to suspend PC has been added. Could you switch to the Testing store and get the latest version of Buddy to test it out?

**Comment by FrogTheFrog** [comment]
Closing as it's already working on windows and linux

**Comment by philhzss** [comment]
Would it be possible to add Hibernate too? I always use hibernate instead of Shutdown/Suspend. But I realise this might be a bit too many buttons now

**Comment by FrogTheFrog** [comment]
> Would it be possible to add Hibernate too? I always use hibernate instead of Shutdown/Suspend. But I realise this might be a bit too many buttons now

Please check https://github.com/FrogTheFrog/moondeck-buddy/pull/43.

I have not tested this on Windows since I don't have time, but you can:
- download the latest build from the PR,
- run the new Buddy version so it can save update the settings.json
- edit settings.json and set the obvious flag to `true`
- restart Buddy
- try to suspend PC via MoonDeck and see if the Buddy tries to hibernate first.

**Comment by philhzss** [comment]
Oh sorry, I just saw you released it and I didn't have time to test it before. I'm sure it works but I'll let you know when I test it. Thank you for adding this!!
