### ISSUE TITLE
Enable HDR when starting session and disable once ended?

### ISSUE THREAD

**Issue by HenryKleinschmidt** [FrogTheFrog/moondeck-buddy#69]
I just setup MoonDeck on my Steam Deck OLED and was wondering if it is possible to enable HDR when starting a MoonDeck session?

**Comment by FrogTheFrog** [comment]
No, because the Moonlight does not support HDR in gamemode yet

**Comment by HenryKleinschmidt** [comment]
Alright thanks for the fast reply :)

**Comment by FrogTheFrog** [comment]
@HenryKleinschmidt Bah, wrong repo sry (did not realize it was about Buddy). If you want to toggle HDR on host:

https://github.com/FrogTheFrog/moondeck-buddy/wiki/Sunshine-setup#windows-disable-hdr-while-streaming

**Comment by HenryKleinschmidt** [comment]
Thank you!
