### ISSUE TITLE
Could you add an option to automatically WOL if moon deck-buddy is offline?

### ISSUE THREAD

**Issue by HenryKleinschmidt** [FrogTheFrog/moondeck-buddy#71]
This would be great for a more seamless experience. 
Currently I have to browse to the Moondeck plugin page, hit "Wake on LAN", browse to the game and finally hit the Moondeck icon.

With this option the user would only have to click the Moondeck icon and wait a _little_ longer if the hosts is waking up.

**Comment by FrogTheFrog** [comment]
I'm already working on this on my free time.

**Comment by HenryKleinschmidt** [comment]
Great to hear!
Thank you for your response :)

**Comment by FrogTheFrog** [comment]
Feature is in the newest MoonDeck version
