### ISSUE TITLE
[Linux] error when compiling with CMake

### ISSUE THREAD

**Issue by spv420** [FrogTheFrog/moondeck-buddy#72]
Running Debian `unstable`, and attempting to compile Moondeck Buddy as my repositories only have QT 6.4.2, not 6.5 as required, which causes the AppImage to crash.

I've ran into an error I cannot seem to fix however, and I'm hoping y'all could help.
```
$ cmake ..
CMake Error at src/lib/os/linux/CMakeLists.txt:13 (find_library):
  Could not find PROCPS_LIBRARY using the following names: proc, procps


-- Configuring incomplete, errors occurred!
$
```

I've verified that `libprocps8` is installed.

**Comment by spv420** [comment]
I've installed `libproc2-0` and `libproc2-dev`, and compiled with `cmake .. -DPROCPS_LIBRARY=/lib/x86_64-linux-gnu/libproc2.a` and I've gotten further but it is now failing with ```
/home/spv/moondeck-buddy/src/lib/os/linux/nativeprocesshandler.cpp:10:10: fatal error: proc/readproc.h: No such file or directory
   10 | #include <proc/readproc.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by FrogTheFrog** [comment]
You'll get no help from me unfortunately as I'm on arch, but it was also pain to setup this library...
