### ISSUE TITLE
Pair Button greyed out

### ISSUE THREAD

**Issue by p5lukas** [FrogTheFrog/moondeck-buddy#75]
Hi, already was paired with the portable Version of moondeckbuddy. Now, if I want to use the installed version, the host allways connects easily, but I am not able to pair, because the option is greyed out. If I download the portable version again, the Prozess of pairing is no problem again.

Already tried to deinstall everything and delete the installation folders several times.
Is there a option to force the pairing again? Or am I doing something wrong?

**Comment by FrogTheFrog** [comment]
Why is the pair button greyed out? What does the status message say in MoonDeck?

**Comment by p5lukas** [comment]
The status for Moondeck Buddy in the host selection was just „Offline“. 

I can reverse from portable to installed later (in a hour) for a picture or something, when u need it.

**Comment by FrogTheFrog** [comment]
The non-portable version is probably blocked by a firewall or something.

**Comment by p5lukas** [comment]
I only have the windows standards, no additional Anti-virus software or something. Where can I check, so that nothing is blocked?

**Comment by FrogTheFrog** [comment]
You can verify if Buddy is reachable outside the host by using the `https://<host_ip>:<buddy_port>/apiVersion` url in a web browser that connected to the same network.

https://github.com/FrogTheFrog/moondeck-buddy/wiki/Troubleshooting#make-sure-that-buddy-is-not-blocked-by-the-firewall

**Comment by FrogTheFrog** [comment]
Try both portable and non-portable to see the difference.

**Comment by p5lukas** [comment]
I will do later and report

**Comment by p5lukas** [comment]
turns out that if i start the portable version, the buddy is online and sais that the certificate is invalid...so i think, everythigs fine.

But if i start the installed version, buddy is shown as offline and "pair" is greyed out. The URL is only reachable on the host PC. Mobile says, not reachable.
