### ISSUE TITLE
[Feature Request] Close big picture with alt+enter after closing game

### ISSUE THREAD

**Issue by Dazzuh** [FrogTheFrog/moondeck-buddy#76]
this is mostly in response to "If disabled, Steam will remain open in bigpicture mode (no way to leave bigpicture without closing Steam without using the UI)."

steam big picture can be quickly closed with the alt+enter keybind, it should be relatively easy to automate finding if the big picture window exists from the window title, focusing it and sending the keybind.

**Comment by FrogTheFrog** [comment]
I will not work on this feature as I don't think it's worth the time, but I welcome PR.
