### ISSUE TITLE
Moondeck buddy won't connect when away from home network

### ISSUE THREAD

**Issue by aj53108** [FrogTheFrog/moondeck-buddy#80]
Moondeck buddy works great when I'm on my home network.  But as soon as I access from a different network it says that buddy is offline.  I've opened ports on router and made sure that windows firewall is allowing moondeckbuddy to pass through.  Still nothing.

**Comment by FrogTheFrog** [comment]
You try these steps to check if buddy is reachable or not https://github.com/FrogTheFrog/moondeck-buddy/wiki/Troubleshooting#windowslinux-buddy-appears-offlinecannot-be-paired. Also, make sure that MoonDeck is using a static IP to connect to Buddy.

**Comment by aj53108** [comment]
Read through that and double checked things.  Buddy is reachable when on my home network, but not when I'm off it.  I do have a static IP address set to my PC that I'm trying to stream from.  Is that when you mean by having MoonDeck use a static IP to connect?  Or do I need to change something else too?

**Comment by aj53108** [comment]
Didn't fix it.  I removed the host and readded it manually.  Address type now says static.  Still won't work remotely.

**Comment by FrogTheFrog** [comment]
> Didn't fix it. I removed the host and readded it manually. Address type now says static. Still won't work remotely.

Well, can you reach it via the browser from other network?

**Comment by aj53108** [comment]
No.  I can only reach it from local network.

**Comment by FrogTheFrog** [comment]
You're using this url `https://<host_ip>:<buddy_port>/apiVersion`, right?

Either way, this is clearly a networking or firewall issue if you can't reach it via the browser. Not much I can do to help you in this case.

**Comment by FrogTheFrog** [comment]
Closing as it has nothing to do with Buddy, but just networking issues
