### ISSUE TITLE
Moondeckbuddy seems to force Steamdeck resolution, how to turn off?

### ISSUE THREAD

**Issue by delano8** [FrogTheFrog/moondeck-buddy#81]
So I've got Sunshine/Moonlight, and use it for 2 devices, my tv, and my Steamdeck. Of course, they are all different resolutions from my pc.

Long story short, tv works great, I've set up a nircmd command (in the "do" tab) that changes my pc to the second monitor being the main, THEN changing the resolution of that, THEN launching the game. Works great for my tv!

However with Moondeckbuddy, something goes wrong.

Whatever I do, it changes my pc resolution to Steamdeck resolution every time, BEFORE the bat file has ran to switch monitor.
I've tried putting the bat command in the "do" tab, and also as a detached command. Doesn't matter, it only starts running these commands after changing my pc resolution. I don't want or need that (because the command also changes the res, of the wanted monitor).

I tried changing moonlight resolution (makes a letterboxed screen on Steamdeck) and turned off the Decky plugin's "pass to moonlight" resolution setting.

Whatever I do, it always changes the res before my bat files had a chance to run.

Of course, everything else still works. But I want it to run on my second (off) monitor, and not changing my main pc resolution.

Thanks for helping!

**Comment by FrogTheFrog** [comment]
Heyo,

In MoonDeck settings disable the option "Pass To Buddy" (or something like that).

**Comment by delano8** [comment]
> Heyo,
> 
> In MoonDeck settings disable the option "Pass To Buddy" (or something like that).

I did that, as mentioned in my post:

I tried changing moonlight resolution (makes a letterboxed screen on Steamdeck) and turned off the Decky plugin's "pass to moonlight" resolution setting.

**Comment by FrogTheFrog** [comment]
There are 2 options:
- Pass to Buddy (disable this as this informs Buddy to change resolution)
- Pass to Moonlight (keep this as these parameters will appear in the do/undo commands)

**Comment by delano8** [comment]
> There are 2 options:
> 
>     * Pass to Buddy (disable this as this informs Buddy to change resolution)
> 
>     * Pass to Moonlight (keep this as these parameters will appear in the do/undo commands)

Oh, oops. That was totally it, and I missed that. I'm sorry. Thanks for helping!
