### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by fulcrum1994** [FrogTheFrog/moondeck-buddy#82]
Hi there! Both moondeck in decky and buddy are updated to the latest versions but I am still seeing version mismatch on my deck. Any tips?

**Comment by AndrewEllis93** [comment]
I had the same issue. I:
- Uninstalled and then reinstalled moondeck buddy
- "Forgot" all hosts in moondeck
- Rebooted my steam deck
- Scanned and added for the host in moondeck again
- Rebooted the host PC
- Paired moondeck buddy (no longer showed version mismatch)
It started working after rebooting the host PC, not sure if the other steps were necessary.

**Comment by FrogTheFrog** [comment]
Maybe you guys forgot to exit MoonDeckBuddy before installing update? @fulcrum1994 Try that and install update again.

**Comment by FrogTheFrog** [comment]
Also, please go to https://localhost:59999/apiVersion on your host, accept the SSL certificate risk an tell me which version is printed (once the Buddy is running)
