### ISSUE TITLE
Can not pair

### ISSUE THREAD

**Issue by iknow2333** [FrogTheFrog/moondeck-buddy#83]
I clicked on pairing on the deck, then entered the code into my computer and clicked OK, nothing happened, after a while this window automatically exited and the deck was still not paired.
![image](https://github.com/FrogTheFrog/moondeck-buddy/assets/103983460/1b7fc3a0-9f94-4d8f-b07a-9a26989fc08e)

**Comment by iknow2333** [comment]
Of course, I turned off the firewall

**Comment by FrogTheFrog** [comment]
Ok, so I didn't take the localization into account it seems... Buddy expects Arabic numerals. Could you please post a screenshot of how it looks on the SteamDeck?

**Comment by iknow2333** [comment]
Actually I did type in Arabic numerals, but you reminded me, I found a workaround on the Internet, which was to modify the region and region formatting in windows, and it worked, anyway, thank you for developing this plugin!
