### ISSUE TITLE
Unable to stream after uninstall

### ISSUE THREAD

**Issue by AlphaBril** [FrogTheFrog/moondeck-buddy#86]
As I got too much difficulties to allow 2 different configuration with moonlight (one 4K for streaming game on playnite on my tv and one lowres for the steamdeck) I decided to remove moondeck (and moonlight) from my steamdeck and stick to the default steam remote play.

However after uninstalling everything properly, I can no longer launch the streaming. I am hit by a nice error:
- Failed to launch stream:
  impossible to launch stream

Do you think it may be from my previous manipulation with moondeck-buddy ? or should I contact steam support as it has nothing to do with it (I bet on the later part, as we are using moonlight so it shouldn't have any impact on steam, but I saw that the buddy server part is interacting with steam on the host) ?

dissociate all, deactivate/reactivate remote play, rebooting both device, nothing worked so far..

**Comment by FrogTheFrog** [comment]
Buddy has nothing to do with it unfortunately. All it does is launch steam similarly like you would launch it via the desktop shortcut.

This is the only direct interaction Buddy has with Steam.

**Comment by FrogTheFrog** [comment]
To add to this, Steam remote play never worked for me from SteamDeck. It would always just show a black screen 😐
