### ISSUE TITLE
It runs the game but black screen with UI on Steam Deck

### ISSUE THREAD

**Issue by rairulyle** [FrogTheFrog/moondeck-buddy#88]
Hello,

I am using this script on my Sunshine 
https://github.com/Nonary/ResolutionAutomation
and I have Moon Deck latest testing v1.7.1 and I have disabled passing of moonlight settings so that it will not overide it.

But what happens is that it runs the script (changes resolution) and runs the game but still the Steam Deck is on Black screen with UI.

And so then I tried to not use the script and just use the option "pass moonlight settings..." on your plugin to see if it works. And it still doesn't. Same issue.

This doesn't happen if run Moonlight instead of Moondeck.

I am also in Steam OS 3.6.8

**Comment by FrogTheFrog** [comment]
It seems to be that the Moonlight is crashing (probably). Have you tried rebooting host and steamdeck? Does the game start on the host?

**Comment by rairulyle** [comment]
> It seems to be that the Moonlight is crashing (probably). Have you tried rebooting host and steamdeck? Does the game start on the host?

Yes it does that start. I've tried restarting as well. I am now tring to setup moondeck from scratch and see.

If still persist. I'll send you a video.

**Comment by rairulyle** [comment]
@FrogTheFrog now thst I have free time. I managed to tinker and made it work. I just habe to change the app launch timeout from 30 to 60. It now works!

**Comment by BigPrimeNumbers** [comment]
This issue is occurring for me, and changing that value does not seem to help.
