### ISSUE TITLE
MoonDeckBuddy won't start in ubuntu 24

### ISSUE THREAD

**Issue by qnlbnsl** [FrogTheFrog/moondeck-buddy#89]
I installed the appimage and can run MoonDeckStream via the exec option but the MoonDeckBuddy won't start until i use sudo in which case it crashes as it cannot find anything under /root/

Is there a way to debug this?

**Comment by FrogTheFrog** [comment]
Sorry for not replying earlier, but you could try to extract the appimage and run the binary directly.
