### ISSUE TITLE
MoonDeck Buddy not syncing latest list of apps

### ISSUE THREAD

**Issue by Rumik** [FrogTheFrog/moondeck-buddy#93]
Hi there!

MoonDeck Buddy isn't syncing all my Sunshine apps - only 22 of them and I have more. What's more, the list it's syncing includes an application that I've deleted.... so it's like it's reading from an old list, a cache somewhere. Can you help me resolve this?

Thanks.

**Comment by FrogTheFrog** [comment]
Buddy is reading the Sunshine config's `apps.json` file directly. Can you please paste it here?

**Comment by Rumik** [comment]
Sure. An example of what I mean is "Madden 25" is still getting synced even though it doesn't exist anymore. And Horizon Forbidden West isn't getting synced even though it's in the list.

{
    "env": {
        "PATH": "$(PATH);$(ProgramFiles(x86))\\Steam"
    },
    "apps": [
        {
            "name": "Desktop",
            "image-path": "desktop.png",
            "exclude-global-prep-cmd": "",
            "elevated": [
                "on"
            ],
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "cmd": "",
            "virtual-display-primary": "false",
            "scale-factor": "100",
            "virtual-display": "false"
        },
        {
            "name": "Steam Big Picture",
            "output": "",
            "cmd": "",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "prep-cmd": [
                {
                    "do": "steam steam:\/\/open\/bigpicture",
                    "undo": "steam steam:\/\/close\/bigpicture",
                    "elevated": "true"
                }
            ],
            "image-path": "steam.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Call of Duty",
            "output": "",
            "cmd": "steam:\/\/rungameid\/16738515402643996672",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Apollo\\config\/covers\/igdb_308961.png",
            "working-dir": "",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Helldivers 2",
            "output": "",
            "cmd": "steam:\/\/rungameid\/553850",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_250616.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Destiny 2",
            "output": "",
            "cmd": "steam:\/\/rungameid\/1085660",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_25657.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Dragon's Dogma 2",
            "output": "",
            "cmd": "steam:\/\/rungameid\/2054970",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "https:\/\/images.igdb.com\/igdb\/image\/upload\/t_cover_big\/co833w.webp",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "No Rest for the Wicked",
            "output": "",
            "cmd": "steam:\/\/rungameid\/1371980",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_279627.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Detroit: Become Human",
            "output": "",
            "cmd": "steam:\/\/rungameid\/1222140",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_14362.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Concord",
            "output": "",
            "cmd": "steam:\/\/rungameid\/2443720",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_250632.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "God of War",
            "output": "",
            "cmd": "steam:\/\/rungameid\/1593500",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_19560.png",
            "working-dir": "",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Diablo IV",
            "output": "",
            "cmd": "steam:\/\/rungameid\/15770705876098220032",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_125165.png",
            "working-dir": "",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "XDefiant",
            "output": "",
            "cmd": "steam:\/\/rungameid\/17892962548353859584",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_159029.png",
            "working-dir": "",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Street Fighter 6",
            "output": "",
            "cmd": "",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_191692.png",
            "working-dir": "steam:\/\/rungameid\/1364780",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "The Last of Us Part I",
            "output": "",
            "cmd": "steam:\/\/rungameid\/14559006996721303552",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_204350.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Ratchet & Clank: Rift Apart",
            "output": "",
            "cmd": "steam:\/\/rungameid\/12965270875149434880",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_134582.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Ghost of Tsushima: Director's Cut",
            "output": "",
            "cmd": "steam:\/\/rungameid\/9793723962717372416",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_153700.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Cyberpunk 2077",
            "output": "",
            "cmd": "steam:\/\/rungameid\/15123299836092219392",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_1877.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Uncharted 4: A Thief's End",
            "output": "",
            "cmd": "steam:\/\/rungameid\/13566176180414971904",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_7331.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Uncharted: The Lost Legacy",
            "output": "",
            "cmd": "steam:\/\/rungameid\/10213603513217318912",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_26193.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "World of Warcraft",
            "output": "",
            "cmd": "steam:\/\/rungameid\/14910278456167104512",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Apollo\\config\/covers\/igdb_275176.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Suicide Squad: Kill the Justice League",
            "image-path": "C:\\Program Files\\Apollo\\config\/covers\/igdb_136627.png",
            "id": "1755240275",
            "exclude-global-prep-cmd": "",
            "elevated": [
                "on"
            ],
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "cmd": "steam:\/\/rungameid\/14010661358035533824",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Horizon Forbidden West",
            "output": "",
            "cmd": "steam:\/\/rungameid\/12061592812425052160",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Apollo\\config\/covers\/igdb_268842.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Indiana Jones and the Great Circle",
            "output": "",
            "cmd": "steam:\/\/rungameid\/11087100591644606464",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Apollo\\config\/covers\/igdb_142415.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "Dead By Daylight",
            "output": "",
            "cmd": "steam:\/\/rungameid\/10705671276300599296",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "C:\\Program Files\\Apollo\\config\/covers\/igdb_18866.png",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "XDefiant",
            "output": "",
            "cmd": "steam:\/\/rungameid\/15636516756875378688",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "prep-cmd": [
                {
                    "do": "cmd \/C \"C:\\Program Files\\Apollo\\tools\\nircmd\\nircmd.exe\" sendkeypress lwin+m",
                    "undo": "",
                    "elevated": "false"
                }
            ],
            "image-path": "",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        },
        {
            "name": "MoonDeckStream",
            "output": "\"C:\\Users\\RBrain\\AppData\\Local\\Programs\\MoonDeckBuddy\\bin\\MoonDeckBuddy.exe\"",
            "cmd": "",
            "exclude-global-prep-cmd": "false",
            "elevated": "true",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "image-path": "",
            "virtual-display-primary": "true",
            "scale-factor": "100",
            "virtual-display": "true"
        }
    ]
}

**Comment by Rumik** [comment]
Oh wait..... I know what's happening. I'm using Apollo, so if Buddy is reading from the apps file, it's looking in the wrong place.

My bad.
