### ISSUE TITLE
Is it possible to use moondeckbuddy for auto resolution change for non-steam game?

### ISSUE THREAD

**Issue by mysteriousHerb** [FrogTheFrog/moondeck-buddy#94]
I would just like to launch into e.g. steam big picture or playnite or any emulated game on my PC. can this be done?

**Comment by FrogTheFrog** [comment]
No. You can either use Sunshine with scripts or this Sunshine build (which should be merged to Sunshine one day):
<https://github.com/FrogTheFrog/Sunshine/pull/2>

If you decide to use either option, be sure to disable "pass to buddy" option in MoonDeck, so that they do not fight over resolution.
