### ISSUE TITLE
Failed to parse unknown arguments: QList("")

### ISSUE THREAD

**Issue by kd8bny** [FrogTheFrog/moondeck-buddy#99]
Using the latest appimage release

Running with --exec MoonDeckBuddy
Or using the symlink for buddy gives the following output, difficulty parsing an empty list when no args are provided.

```
Failed to parse unknown arguments: QList("")
```

Executing the binary directly, it starts just fine

**Comment by FrogTheFrog** [comment]
I have recreated the release with a fix for AppImage.

I know, I know... I should probably create a new release for this, but I didn't want to increment the version just for packaging issues...
